### ISSUE TITLE
Arrange M&Ms by color

### ISSUE THREAD

**Issue by ax3l** [RevathiJambunathan/ATPESC_Issues#5]
New task proposed by @RevathiJambunathan:

https://github.com/RevathiJambunathan/ATPESC_Issues/issues/2#issuecomment-519663415

## Dependencies

- [x] #2

**Comment by RevathiJambunathan** [comment]
![20190808_150852](https://user-images.githubusercontent.com/41089244/62734595-fda03200-b9ee-11e9-8ac7-f404e514d639.jpg)

**Comment by RevathiJambunathan** [comment]
Thank you @ax3l :) This looks great!

**Comment by ax3l** [comment]
cc @drladiges please review ;)
